trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - '.*' # skip every hidden file change in root dir
      - '**/.*' # skip every hidden file change in any dir below root dir
pool:
  vmImage: ubuntu-latest

stages:
  - stage: init_ci
    # first stage can't be conditional therefore we create one if we want to have some approvals in the pipeline
    displayName: Init CI
    jobs:
      - job: init
        displayName: 'Init'
        steps:
          - checkout: none
          - bash: |
              echo "This is init stage, as first one can't be conditional. Important CI variables:"
              echo "Build reason is: ${BUILD_REASON}."
              echo "Source branch is: ${SOURCE_BRANCH}."
              echo "Current UTC time is $(date -u +%k%M)."
            displayName: 'Print variables'
  - stage: build_backend
    displayName: Build Backend Application
    jobs:
      - job: agent_preparation
        displayName: Agent Preparation
        steps:
          - checkout: self
          - bash: |
              yarn install --frozen-lockfile
              yarn run type-check
              yarn run lint
            displayName: "Dependencies preparation"
          # DockerFile + DockerCompose
          - bash: echo Hello, world!
            displayName: 'Run a one-line script just because'
