version: '3.4'

services:
  shared:
    build:
      context: .
      dockerfile: docker/Dockerfile.shared.local
    restart: always
    volumes:
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.local
    restart: always
    depends_on:
      - shared
      - postgres
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist
    env_file:
      - backend/.env
    environment:
      - PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_DATABASE=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    ports:
      - 8080:8080

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
  shared:
