version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - backend/.env.docker
    environment:
      - PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_DATABASE=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    ports:
      - 8080:8080

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
