version: '3.4'

services:
  shared:
    build:
      context: .
      dockerfile: docker/Dockerfile.shared.local
    restart: always
    volumes:
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend.local
    restart: always
    depends_on:
      - shared
      - postgres
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist
    env_file:
      - backend/.env.docker
    environment:
      - PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_DATABASE=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
    ports:
      - 8080:8080

  admin:
    build:
      context: .
      dockerfile: docker/Dockerfile.admin
    restart: always
    depends_on:
      - shared
      - postgres
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist
    env_file:
      - backend/.env.docker
    environment:
      - ADMIN_PORT=8081
      - ADMIN_DISABLE_AUTH=true
      - DATABASE_HOST=postgres
      - DATABASE_DATABASE=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=public
    ports:
      - 8081:8081

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.local
    restart: always
    depends_on:
      - shared
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/public:/usr/src/app/frontend/public
      - ./shared/src:/usr/src/app/shared/src
      - shared:/usr/src/app/shared/dist
    environment:
      - VITE_PROXY_HOST=backend:8080
    ports:
      - 3000:3000

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
  shared:
