FROM node:16-alpine

ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ ./.yarn/
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/
COPY shared/package.json ./shared/

RUN yarn install --immutable

COPY . .

WORKDIR /usr/src/app/shared
RUN yarn build

WORKDIR /usr/src/app/frontend
RUN yarn build

WORKDIR /usr/src/app/backend
RUN yarn copy-client
RUN yarn build

CMD ["yarn", "start:prod"]

