FROM node:16-alpine

RUN apk --no-cache add --virtual .builds-deps build-base python3

WORKDIR /usr/src/app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/ ./.yarn/
COPY eslint-plugin/package.json ./eslint-plugin/
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/
COPY shared/package.json ./shared/

RUN yarn install --immutable

COPY . .

WORKDIR /usr/src/app/shared

CMD ["yarn", "dev"]

