export const ELEMENTARY_SCOPE = 'PODSTAWOWY';
export const ADVANCED_SCOPE = 'SPECJALISTYCZNY';
export const REQUIRED_AMOUNT_OF_ONE_POINT_QUESTIONS = 4;
export const REQUIRED_AMOUNT_OF_TWO_POINT_QUESTIONS = 6;
export const REQUIRED_AMOUNT_OF_THREE_POINT_QUESTIONS = 10;
export const REQUIRED_AMOUNT_OF_ONE_POINT_ADVANCED_QUESTIONS = 2;
export const REQUIRED_AMOUNT_OF_TWO_POINT_ADVANCED_QUESTIONS = 4;
export const REQUIRED_AMOUNT_OF_THREE_POINT_ADVANCED_QUESTIONS = 6;
